version: '3.9'
services:
  webapi:
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    container_name: webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
